site_name: swarmbase.ai
site_url: https://github.com/Go-Pomegranate/Swarmy.ai
nav:
  - Start: index.md
  - Home: documentation.md
  - About us: aboutus.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: grey
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Go-Pomegranate/Swarmy.ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/swarmbase-ai/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list


copyright: |
  &copy; 2024 <a href="https://github.com/Go-Pomegranate/Swarmy.ai"  target="_blank" rel="noopener">Swarmbase.ai</a>

